In [1]:
%pip install numpy pandas matplotlib


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print("Everything works ✅")


Everything works ✅


In [10]:
import numpy as np



In [9]:
arr1 = np.arange(1, 11)



In [8]:
arr2 = np.random.randint(1, 10, size=(3, 3))


In [14]:


arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:


arr2


array([[6, 1, 6],
       [5, 9, 1],
       [7, 5, 3]], dtype=int32)

In [5]:

arr1.sum(), arr1.mean(), arr1.max()



(np.int64(55), np.float64(5.5), np.int64(10))

In [6]:
arr1 * 2



array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
np.where(arr1 > 5, 0, arr1)

array([1, 2, 3, 4, 5, 0, 0, 0, 0, 0])